from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 300)
        MainWindow.setMinimumSize(QtCore.QSize(350, 300))
        MainWindow.setMaximumSize(QtCore.QSize(350, 300))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vote_option_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_option_button.setGeometry(QtCore.QRect(110, 100, 131, 51))
        self.vote_option_button.setObjectName("vote_option_button")
        self.exit_option_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_option_button.setGeometry(QtCore.QRect(110, 170, 131, 51))
        self.exit_option_button.setObjectName("exit_option_button")
        self.welcome_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(100, 40, 161, 41))
        self.welcome_label.setScaledContents(False)
        self.welcome_label.setObjectName("welcome_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Terminal"))
        self.vote_option_button.setText(_translate("MainWindow", "Vote"))
        self.exit_option_button.setText(_translate("MainWindow", "Exit"))
        self.welcome_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Welcome, choose an action...</span></p></body></html>"))

class Ui_input_voting_terminal(object):
    def setupUi(self, input_voting_terminal):
        input_voting_terminal.setObjectName("input_voting_terminal")
        input_voting_terminal.resize(300, 300)
        input_voting_terminal.setMinimumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(parent=input_voting_terminal)
        self.centralwidget.setObjectName("centralwidget")
        self.candidates_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidates_label.setGeometry(QtCore.QRect(30, 60, 111, 21))
        self.candidates_label.setObjectName("candidates_label")
        self.candidate1_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate1_label.setGeometry(QtCore.QRect(70, 90, 41, 16))
        self.candidate1_label.setObjectName("candidate1_label")
        self.candidate2_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate2_label.setGeometry(QtCore.QRect(70, 130, 41, 16))
        self.candidate2_label.setObjectName("candidate2_label")
        self.candidate3_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate3_label.setGeometry(QtCore.QRect(70, 170, 41, 16))
        self.candidate3_label.setObjectName("candidate3_label")
        self.radio_can1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_can1.setGeometry(QtCore.QRect(30, 85, 20, 21))
        self.radio_can1.setText("")
        self.radio_can1.setObjectName("radio_can1")
        self.radio_can2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_can2.setGeometry(QtCore.QRect(30, 125, 51, 21))
        self.radio_can2.setText("")
        self.radio_can2.setObjectName("radio_can2")
        self.radio_can3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_can3.setGeometry(QtCore.QRect(30, 170, 31, 16))
        self.radio_can3.setText("")
        self.radio_can3.setObjectName("radio_can3")
        self.radio_custom = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_custom.setGeometry(QtCore.QRect(30, 210, 16, 16))
        self.radio_custom.setText("")
        self.radio_custom.setObjectName("radio_custom")
        self.custom_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.custom_label.setGeometry(QtCore.QRect(70, 210, 151, 16))
        self.custom_label.setObjectName("custom_label")
        self.voterid_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.voterid_input.setGeometry(QtCore.QRect(120, 20, 113, 20))
        self.voterid_input.setObjectName("voterid_input")
        self.voterid_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.voterid_label.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.voterid_label.setObjectName("voterid_label")
        self.error_candidate_name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_candidate_name_label.setGeometry(QtCore.QRect(40, 260, 231, 20))
        self.error_candidate_name_label.setText("")
        self.error_candidate_name_label.setObjectName("error_candidate_name_label")
        self.custom_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.custom_input.setGeometry(QtCore.QRect(70, 230, 113, 20))
        self.custom_input.setText("")
        self.custom_input.setObjectName("custom_input")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(210, 220, 61, 41))
        self.submit_button.setObjectName("submit_button")
        input_voting_terminal.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=input_voting_terminal)
        self.statusbar.setObjectName("statusbar")
        input_voting_terminal.setStatusBar(self.statusbar)

        self.retranslateUi(input_voting_terminal)
        QtCore.QMetaObject.connectSlotsByName(input_voting_terminal)

    def retranslateUi(self, input_voting_terminal):
        _translate = QtCore.QCoreApplication.translate
        input_voting_terminal.setWindowTitle(_translate("input_voting_terminal", "Voting Terminal"))
        self.candidates_label.setText(_translate("input_voting_terminal", "Canidates"))
        self.candidate1_label.setText(_translate("input_voting_terminal", "Bianca"))
        self.candidate2_label.setText(_translate("input_voting_terminal", "Jack"))
        self.candidate3_label.setText(_translate("input_voting_terminal", "Nicole"))
        self.custom_label.setText(_translate("input_voting_terminal", "Enter Custom Candidate"))
        self.voterid_label.setText(_translate("input_voting_terminal", "Enter Voter ID"))
        self.submit_button.setText(_translate("input_voting_terminal", "Submit"))
